project_id = "inwsvuynfkxhswtzgggq"

[functions.sync-systembolaget-data]
verify_jwt = false

[functions.batch-sync-systembolaget]
verify_jwt = false

[functions.test-wine-insert]
verify_jwt = false

[functions.firecrawl-launch-sync]
verify_jwt = false

[functions.sync-vinmonopolet]
verify_jwt = false

[functions.scrape-vinmonopolet]
verify_jwt = false

[functions.sync-alko]
verify_jwt = false